id: Q24WII6cbgI
createdat: ""
updatedat: ""
promotedat: null
width: 5184
height: 3456
color: '#262626'
description: Maroon bells during the summer, we hiked up with a group of people and
  had this amazing view.
altdescription: ""
urls:
  raw: https://images.unsplash.com/photo-1611965581519-1f5a5ee98178?ixid=MXwxOTEyNTB8MHwxfHJhbmRvbXx8fHx8fHx8&ixlib=rb-1.2.1
  full: https://images.unsplash.com/photo-1611965581519-1f5a5ee98178?crop=entropy&cs=srgb&fm=jpg&ixid=MXwxOTEyNTB8MHwxfHJhbmRvbXx8fHx8fHx8&ixlib=rb-1.2.1&q=85
  regular: https://images.unsplash.com/photo-1611965581519-1f5a5ee98178?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MXwxOTEyNTB8MHwxfHJhbmRvbXx8fHx8fHx8&ixlib=rb-1.2.1&q=80&w=1080
  small: https://images.unsplash.com/photo-1611965581519-1f5a5ee98178?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MXwxOTEyNTB8MHwxfHJhbmRvbXx8fHx8fHx8&ixlib=rb-1.2.1&q=80&w=400
  thumb: https://images.unsplash.com/photo-1611965581519-1f5a5ee98178?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MXwxOTEyNTB8MHwxfHJhbmRvbXx8fHx8fHx8&ixlib=rb-1.2.1&q=80&w=200
links:
  self: https://api.unsplash.com/photos/Q24WII6cbgI
  html: https://unsplash.com/photos/Q24WII6cbgI
  download: https://unsplash.com/photos/Q24WII6cbgI/download
  downloadlocation: ""
categories: []
likes: 0
likedbyuser: false
currentusercollections: []
sponsorship: null
user:
  id: UlTJNcnlEBI
  updatedat: ""
  username: pqcrtivephoto
  name: Heyzeus Lozoya
  firstname: ""
  lastname: ""
  twitterusername: ""
  portfoliourl: ""
  bio: "Capturing one day at a time, one smile a day and maybe a moment of existence
    each time I see through the viewfinder.\r\n.\r\n.\r\n.\r\n#positivitycreative"
  location: Colorado Springs, Colorado
  links:
    self: https://api.unsplash.com/users/pqcrtivephoto
    html: https://unsplash.com/@pqcrtivephoto
    photos: https://api.unsplash.com/users/pqcrtivephoto/photos
    likes: https://api.unsplash.com/users/pqcrtivephoto/likes
    portfolio: https://api.unsplash.com/users/pqcrtivephoto/portfolio
    following: https://api.unsplash.com/users/pqcrtivephoto/following
    followers: https://api.unsplash.com/users/pqcrtivephoto/followers
  profileimage:
    small: ""
    medium: ""
    large: ""
  instagramusername: ""
  totalcollections: 0
  totallikes: 0
  totalphotos: 0
  acceptedtos: false
exif:
  make: Canon
  model: Canon EOS 7D
  exposuretime: ""
  aperture: "6.3"
  focallength: ""
  iso: 400
location:
  title: Maroon Bells, Colorado, USA
  name: Maroon Bells, Colorado, USA
  city: null
  country: United States
  position:
    latitude: 39.070849
    longitude: -106.988992
views: 68645
downloads: 78
