id: f1gjQmSTKRo
createdat: ""
updatedat: ""
promotedat: null
width: 4974
height: 3456
color: '#8cd9f3'
description: ""
altdescription: ""
urls:
  raw: https://images.unsplash.com/photo-1612935298907-2bef9d051b56?ixid=MXwxOTEyNTB8MHwxfHJhbmRvbXx8fHx8fHx8&ixlib=rb-1.2.1
  full: https://images.unsplash.com/photo-1612935298907-2bef9d051b56?crop=entropy&cs=srgb&fm=jpg&ixid=MXwxOTEyNTB8MHwxfHJhbmRvbXx8fHx8fHx8&ixlib=rb-1.2.1&q=85
  regular: https://images.unsplash.com/photo-1612935298907-2bef9d051b56?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MXwxOTEyNTB8MHwxfHJhbmRvbXx8fHx8fHx8&ixlib=rb-1.2.1&q=80&w=1080
  small: https://images.unsplash.com/photo-1612935298907-2bef9d051b56?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MXwxOTEyNTB8MHwxfHJhbmRvbXx8fHx8fHx8&ixlib=rb-1.2.1&q=80&w=400
  thumb: https://images.unsplash.com/photo-1612935298907-2bef9d051b56?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MXwxOTEyNTB8MHwxfHJhbmRvbXx8fHx8fHx8&ixlib=rb-1.2.1&q=80&w=200
links:
  self: https://api.unsplash.com/photos/f1gjQmSTKRo
  html: https://unsplash.com/photos/f1gjQmSTKRo
  download: https://unsplash.com/photos/f1gjQmSTKRo/download
  downloadlocation: ""
categories: []
likes: 1
likedbyuser: false
currentusercollections: []
sponsorship: null
user:
  id: _v4eWnKV5GM
  updatedat: ""
  username: joylynn_goh
  name: Joylynn Goh
  firstname: ""
  lastname: ""
  twitterusername: ""
  portfoliourl: ""
  bio: Finding beauty in the ordinary
  location: ""
  links:
    self: https://api.unsplash.com/users/joylynn_goh
    html: https://unsplash.com/@joylynn_goh
    photos: https://api.unsplash.com/users/joylynn_goh/photos
    likes: https://api.unsplash.com/users/joylynn_goh/likes
    portfolio: https://api.unsplash.com/users/joylynn_goh/portfolio
    following: https://api.unsplash.com/users/joylynn_goh/following
    followers: https://api.unsplash.com/users/joylynn_goh/followers
  profileimage:
    small: ""
    medium: ""
    large: ""
  instagramusername: ""
  totalcollections: 0
  totallikes: 0
  totalphotos: 0
  acceptedtos: false
exif:
  make: ""
  model: ""
  exposuretime: ""
  aperture: ""
  focallength: ""
  iso: 0
location:
  title: Yosemite Valley, CA, USA
  name: Yosemite Valley, CA, USA
  city: Yosemite Valley
  country: United States
  position:
    latitude: 37.74557
    longitude: -119.593604
views: 12045
downloads: 54
