package function

import (
	"io/ioutil"
	"log"
	"os"
)

// CreateDir create a directory, even if not existent, given its name
func CreateDir(name string) bool {
	_, err := os.Stat(name)
	if os.IsNotExist(err) {
		errDir := os.MkdirAll(name, os.ModePerm)
		if errDir != nil {
			log.Fatal(err)
			return false
		}
	}

	return true
}

// CreateTempDir creates a new temporary directory in the directory dir.
// The directory name is generated by taking pattern and applying a random string to the end
func CreateTempDir(dir string, pattern string) (string, error) {
	dir, err := ioutil.TempDir(dir, pattern)
	if err != nil {
		log.Fatal(err)
	}
	return dir, err
}
