.PHONY: test/unsplash/help
test/unsplash/help:
	cd generated-project-0 && clencli unsplash --help

.PHONY: test/unsplash/query
test/unsplash/query:
	cd generated-project-0 && clencli unsplash --query dogs