name: Build
on: [push]
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.2'
      - run: go version 
      - run: go env 
      - run: go generate ./...
      - name: Run go test
        run: |
          export UNSPLASH_ACCESS_KEY=${{ secrets.UNSPLASH_ACCESS_KEY }}
          export UNSPLASH_SECRET_KEY=${{ secrets.UNSPLASH_SECRET_KEY }}
          cd cobra/cmd && go test -v
      - name: Run go build
        run: mkdir bin/ && go build -o bin/clencli