name: Build
on: [push]
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.6'
      - run: apt-get install -y git 
      - run: go version 
      - run: go env
      - run: go generate ./...
      - name: Run go test
        run: make go/test
      - name: Run go build
        run: mkdir bin/ && go build -o bin/clencli